import { Metadata } from "next";
import React, { Suspense } from "react";
import { Refine } from "@refinedev/core";
import { DevtoolsProvider } from "@providers/devtools";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import {
  useNotificationProvider,
  RefineSnackbarProvider,
} from "@refinedev/mui";
import routerProvider from "@refinedev/nextjs-router";

import { AppIcon } from "@components/app-icon";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";
import { ColorModeContextProvider } from "@contexts/color-mode";

import HouseIcon from "@mui/icons-material/House";
import PersonIcon from "@mui/icons-material/Person";
import PeopleIcon from "@mui/icons-material/People";
import AssetInstanceIcon from "@mui/icons-material/AcUnit";
import DashboardIcon from "@mui/icons-material/Dashboard";
import MapIcon from "@mui/icons-material/Map";
import ServiceIcon from "@mui/icons-material/DesignServices";

import "./_main.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={"dark"}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    authProvider={authProviderClient}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    resources={[
                      {
                        name: "dashboard",
                        list: "/dashboard",
                        icon: <DashboardIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },

                      {
                        name: "customers",
                        list: "/customers",
                        create: "/customers/create",
                        edit: "/customers/edit/:id",
                        icon: <PersonIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },
                      {
                        name: "suppliers",
                        list: "/suppliers",
                        create: "/suppliers/create",
                        edit: "/suppliers/edit/:id",
                        icon: <PeopleIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },
                      {
                        name: "addresses",
                        list: "/addresses",
                        create: "/addresses/create",
                        edit: "/addresses/edit/:id",
                        icon: <MapIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },
                      {
                        name: "Assets",
                        list: "/assets",
                        create: "/assets/create",
                        edit: "/assets/edit/:id",
                        icon: <AssetInstanceIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },
                      {
                        name: "sites",
                        list: "/sites",
                        edit: "/sites/edit/:id",
                        icon: <HouseIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },
                      {
                        name: "Service History Records",
                        list: "/service_history_records",
                        create: "/service_history_records/create",
                        edit: "/service_history_records/edit/:id",
                        icon: <ServiceIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },
                      {
                        name: "addresses",
                        list: "/addresses",
                        create: "/addresses/create",
                        edit: "/addresses/edit/:id",
                        icon: <MapIcon />,
                        meta: {
                          canDelete: false,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "gOa9Je-8GIbbE-n0HkY2",
                      title: { text: "Refine Project", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
